name: Lint

on:
  pull_request_target:

concurrency:
  # Skip intermediate builds: always.
  # Cancel intermediate builds: only if it is a pull request build.
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}

jobs:
  JuliaFormatter:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}
          token: ${{ secrets.PAT }}
      - uses: julia-actions/setup-julia@v1
        with:
          version: 1
          arch: x64
      - uses: julia-actions/julia-buildpkg@v1
      - name: Install JuliaFormatter and format
        run: |
          julia --color=yes -e 'import Pkg; Pkg.add("JuliaFormatter")'
          julia --color=yes -e 'using JuliaFormatter; format(".")'
      - name: Commit changes and push
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: 'style: formatting fixes'
